title: Junaid Din
logo: /images/Profile Pic.jpg
description: Data Enthusiast | Portfolio projects highlighted in blue. Click the blue links to access the GitHub Repositories for the projects shown.
#show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: false
